SIP-371: update: package version bump
sourcetoad/Logger pull request #38
Opened 2023-02-27 21:02 UTC by MOFFROUGH

2023-02-27 21:09 UTC, iBotPeaches requested changes
Was dropping 9 needed for something? I imagined we could keep 9/10 in parallel for this unless we encountered something.

2023-02-28 18:37 UTC, iBotPeaches requested changes
I don't see L10 allowed

2023-03-01 16:01 UTC, iBotPeaches submitted a review, later dismissed
Seems odd that all formatting changed on `composer.json`, unless it was invalid from get go.

2023-03-01 16:14 UTC, iBotPeaches approved these changes

2023-03-01 16:14 UTC, NilsDelaguardia approved these changes

2023-03-01 17:08 UTC, erik-perri approved these changes

2023-03-02 15:26 UTC, frankspress approved these changes

2023-03-02 15:41 UTC, rbondoc96 approved these changes

2023-03-02 15:43 UTC, merged